[application]

# dioxus project name
name = "baba-pet"

# default platfrom
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "docs"

# resource (static) file folder
asset_dir = "static"

[web.app]

# HTML title tag content
title = "OwO What is this?"

[web.watcher]

index_on_404 = true

watch_path = ["src", "examples"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["assets/baba.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []

[bundler]
# Bundle identifier
identifier = "io.github.babakinha"

# Bundle publisher
publisher = "babakinha"

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["static/*"]

# Bundle copyright
copyright = "Babakinha"

# Bundle category
category = "Utility"

# Bundle short description
short_description = "Baba's Website :3"

# Bundle long description
long_description = """
Baba's Website :3
"""
